# Generated by Django 6.0.7 on 2026-07-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_application_is_shortlisted"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="application",
            new_name="jobs_applic_organiz_2e2256_idx",
            old_name="jobs_applic_organiz_short_idx",
        ),
    ]
